#-----------------------------#
#    General configuration    #
#-----------------------------#

# Version number
version: 0.1.{build}-{branch}

# Branches to build
branches:
  only:
    - master
    - develop
    - feature/appveyor_integration

# Maximum number of concurrent jobs
max_jobs: 1

#-----------------------------#
#  Environment configuration  #
#-----------------------------#

environment:
  matrix:
    - compiler: msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64

# Clone directory
clone_folder: c:\vcv-link-build\vcv-link

# Scripts that are called at very beginning, before repo cloning
before_build:
  - cd c:\vcv-link-build
  - git clone --recursive https://github.com/VCVRack/Rack.git vcv-rack
  - cd vcv-rack
  - git checkout v0.5.0
  - git submodule update --init --recursive
  - make dep
  - make
  
install:
  #- PATH C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;"%PATH%""
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm --noprogressbar -S git make tar unzip mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake"

#-----------------------------#
#     Build configuration     #
#-----------------------------#

# Build platform and configuration
platform: Any CPU
configuration: Release

build_script:
  - xcopy c:\vcv-link-build\vcv-link c:\vcv-link-build\vcv-rack\plugins\vcv-link /s /h /e /k /f /c /i
  - cd c:\vcv-link-build\vcv-rack\plugins\vcv-link
  - make
